// GENERATED by design/tokens/build.mjs from design/tokens/tokens.json.
// DO NOT EDIT BY HAND — edit the JSON and re-run the generator.
// Editing this file directly reintroduces exactly the four-surface drift
// E3.1 exists to remove.

import type { MantineColorsTuple } from "@mantine/core";

export const teal: MantineColorsTuple = [
  "#e6f7f5", "#c0ebe6", "#93ddd4", "#63cfc1", "#3ec3b3", "#0B5FA5", "#0a5593", "#08497f", "#073d6b", "#063157",
];
export const gold: MantineColorsTuple = [
  "#fef6e7", "#fce8c2", "#fad89a", "#f8c86f", "#f6ba4d", "#E9A13B", "#d4902f", "#c07f22", "#a56b1a", "#8a5813",
];
export const coral: MantineColorsTuple = [
  "#ffeef0", "#ffd7dc", "#ffb0ba", "#fd8797", "#fc6478", "#EF6E7B", "#e05e6c", "#d14f5d", "#b8404e", "#9e323f",
];
export const emerald: MantineColorsTuple = [
  "#e9fbef", "#c6f5d6", "#9aecb8", "#6ce399", "#45dc80", "#22C55E", "#1eb054", "#199748", "#147e3c", "#0f6530",
];
export const warn: MantineColorsTuple = [
  "#fef5e6", "#fce4bd", "#fad090", "#f8bc61", "#f6ad3d", "#F59E0B", "#e08e08", "#c67c06", "#ac6a05", "#925903",
];
export const danger: MantineColorsTuple = [
  "#fdecec", "#fbd0d0", "#f8afaf", "#f58d8d", "#F37373", "#EF4444", "#d93c3c", "#bf3232", "#a52929", "#8b2020",
];
export const review: MantineColorsTuple = [
  "#e6f7fb", "#c3ecf4", "#93dcea", "#5fc9df", "#33B6D1", "#0E9BB8", "#0c86a0", "#0a6f86", "#08586b", "#064451",
];

// Palette-tinted neutrals, not Mantine's slate default (mandate §1.3).
export const dark: MantineColorsTuple = [
  "#EEF6FF", "#CFE2F5", "#AFC8E0", "#93AEC9", "#5B7A96", "#2C4C6B", "#1E3A54", "#122740", "#0B1A2A", "#050F1A",
];

export const palettes = { teal, gold, coral, emerald, warn, danger, review, dark };

/** Resolved semantic roles per theme — the same values the other three
 *  surfaces render, because they come from the same JSON. */
export const semantic = {
  light: {
    brand: "#0B5FA5",
    onBrand: "#FFFFFF",
    success: "#22C55E",
    warning: "#F59E0B",
    critical: "#EF4444",
    review: "#0E9BB8",
    accent: "#E9A13B",
    cta: "#EF6E7B",
    brandInk: "#0B5FA5",
    successInk: "#147e3c",
    warningInk: "#925903",
    criticalInk: "#bf3232",
    reviewInk: "#0a6f86",
    accentInk: "#8a5813",
    ctaInk: "#b8404e",
    appBg: "#F7F9FC",
    surface: "#FFFFFF",
    surfaceAlt: "#EEF4FB",
    border: "#D5E3F2",
    borderStrong: "#6E8FB3",
    textPrimary: "#0C1F33",
    textSecondary: "#51677F",
    textDisabled: "#8CA2BC",
  },
  dark: {
    brand: "#4DA3E8",
    onBrand: "#04211D",
    success: "#22C55E",
    warning: "#F59E0B",
    critical: "#F37373",
    review: "#33B6D1",
    accent: "#F5B85C",
    cta: "#FF8A95",
    brandInk: "#4DA3E8",
    successInk: "#22C55E",
    warningInk: "#F59E0B",
    criticalInk: "#F37373",
    reviewInk: "#33B6D1",
    accentInk: "#F5B85C",
    ctaInk: "#FF8A95",
    appBg: "#050F1A",
    surface: "#0B1A2A",
    surfaceAlt: "#122740",
    border: "#1E3A54",
    borderStrong: "#43708F",
    textPrimary: "#EEF6FF",
    textSecondary: "#93AEC9",
    textDisabled: "#5B7A96",
  },
} as const;

/** Role name -> Mantine colour key, so page code reads by role. */
export const roleColor = {
  brand: "teal",
  success: "emerald",
  warning: "warn",
  critical: "danger",
  review: "review",
  accent: "gold",
  cta: "coral",
} as const;

/** Domain status -> semantic role. ONE meaning on all four surfaces.
 *  The pending family is `review` (cyan-teal), never `warning`. */
export const statusRole = {
  APPROVED: "success",
  VERIFIED: "success",
  COMPLETED: "success",
  ACTIVE: "success",
  PAID: "success",
  ONLINE: "success",
  ACTIVE_USER: "success",
  PENDING: "review",
  UNDER_REVIEW: "review",
  MANUAL_REVIEW: "review",
  PROCESSING: "review",
  AWAITING_DEPOSIT: "review",
  AWAITING_CONFIRMATION: "review",
  VERIFICATION: "review",
  SUBMITTED: "review",
  RETRY: "warning",
  REJECTED: "critical",
  FAILED: "critical",
  DISPUTED: "critical",
  CANCELLED: "critical",
  OVERDUE: "critical",
  OFFLINE: "critical",
  DEPOSITED: "accent",
  REFUNDED: "accent",
  UNSUBMITTED: "textSecondary",
  NOT_SUBMITTED: "textSecondary",
} as const;

export type StatusKey = keyof typeof statusRole;

/** Status chip fill/ink/border per theme. Stated, not derived from a library's
 *  soft-variant rule — see the generator's note: that rule puts 25 of 28 chips
 *  under the 4.5:1 text floor on this palette. */
export const statusChip = {
  "light": {
    "success": {
      "fill": "#e9fbef",
      "ink": "#147e3c",
      "border": "#9aecb8"
    },
    "warning": {
      "fill": "#fef5e6",
      "ink": "#925903",
      "border": "#fad090"
    },
    "critical": {
      "fill": "#fdecec",
      "ink": "#bf3232",
      "border": "#f8afaf"
    },
    "review": {
      "fill": "#e6f7fb",
      "ink": "#0a6f86",
      "border": "#93dcea"
    },
    "accent": {
      "fill": "#fef6e7",
      "ink": "#8a5813",
      "border": "#fad89a"
    },
    "textSecondary": {
      "fill": "#EEF4FB",
      "ink": "#51677F",
      "border": "#D5E3F2"
    }
  },
  "dark": {
    "success": {
      "fill": "#0E3231",
      "ink": "#22C55E",
      "border": "#13543C"
    },
    "warning": {
      "fill": "#2C2C26",
      "ink": "#F59E0B",
      "border": "#5B471F"
    },
    "critical": {
      "fill": "#2B2634",
      "ink": "#F37373",
      "border": "#5A3843"
    },
    "review": {
      "fill": "#113041",
      "ink": "#33B6D1",
      "border": "#194F63"
    },
    "accent": {
      "fill": "#2C3031",
      "ink": "#F5B85C",
      "border": "#5B503B"
    },
    "textSecondary": {
      "fill": "#122740",
      "ink": "#93AEC9",
      "border": "#1E3A54"
    }
  }
} as const;

/** The chip colours for a status in the active scheme. Unknown statuses get the
 *  muted pair rather than a colour that would imply a recognised state. */
export function statusChipStyle(status: string, scheme: "light" | "dark") {
  const role = statusRole[status.toUpperCase() as StatusKey] ?? "textSecondary";
  const table = statusChip[scheme] as Record<string, { fill: string; ink: string; border: string }>;
  return table[role] ?? table.textSecondary;
}

/** Mantine colour key for a domain status; unknown statuses get no colour
 *  assertion, they render as muted text. */
export function statusColorKey(status: string): string | undefined {
  const role = statusRole[status.toUpperCase() as StatusKey];
  if (!role || role === "textSecondary") return undefined;
  return roleColor[role as keyof typeof roleColor];
}

export const radius = {"input":2,"button":4,"card":6,"circle":999} as const;

export const motion = {"fast":160,"base":260,"slow":420,"ease":"cubic-bezier(0.16, 1, 0.3, 1)"} as const;

export const shadowHairline = "0 1px 2px rgba(7,19,16,.06)";
