// E3.1 token generator — emits each surface's theme artifact FROM
// design/tokens/tokens.json, so the four surfaces can no longer drift by hand.
//
// Run:  node design/tokens/build.mjs         (writes)
//       node design/tokens/build.mjs --check (writes nothing, exits 1 if stale)
//
// What this does NOT do: replace the hand-written theme files wholesale. Each
// surface keeps its own theme file with its own structure, prose and
// stack-specific concerns (Mantine component defaults, Flutter's ThemeData
// wiring, the kiosk's viewport-derived type scale) and CONSUMES the generated
// file. That keeps every existing call site working, keeps the diff reviewable,
// and means a token change is a regenerate rather than a rewrite.

import { writeFileSync, readFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import {
  loadTokens,
  resolveRef,
  resolveSemantic,
  rampSteps,
  REPO_ROOT,
  hexToRgb,
} from "./lib.mjs";

const CHECK_ONLY = process.argv.includes("--check");
const tokens = loadTokens();

const LINES = [
  "GENERATED by design/tokens/build.mjs from design/tokens/tokens.json.",
  "DO NOT EDIT BY HAND — edit the JSON and re-run the generator.",
  "Editing this file directly reintroduces exactly the four-surface drift",
  "E3.1 exists to remove.",
];
/** `//`-style banner, for Dart and TypeScript. */
const BANNER = LINES.map((l) => `// ${l}`).join("\n");
/** Block-comment banner, for CSS. `extra` continues inside the same comment. */
const CSS_BANNER = (extra = "") =>
  `/* ${LINES.join("\n   ")}${extra ? `\n\n   ${extra}` : ""} */`;

const light = resolveSemantic(tokens, "light");
const dark = resolveSemantic(tokens, "dark");
const ROLES = Object.keys(light);

/** rgba(r, g, b, a) from a hex + alpha — the kiosk's glow colours. */
function rgba(hex, alpha) {
  const [r, g, b] = hexToRgb(hex);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

function dartColor(hex) {
  return `Color(0xFF${String(hex).replace(/^#/, "").toUpperCase()})`;
}

const written = [];
const stale = [];

function emit(relPath, contents) {
  const abs = join(REPO_ROOT, relPath);
  const prev = existsSync(abs) ? readFileSync(abs, "utf8") : null;
  if (prev === contents) return;
  if (CHECK_ONLY) {
    stale.push(relPath);
    return;
  }
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, contents, "utf8");
  written.push(relPath);
}

// ── Flutter ────────────────────────────────────────────────────────────────
// Emitted as plain constants plus a per-theme resolver. app_colors.dart
// delegates to these so its ~100 existing `AppColors.x` call sites keep
// working unchanged.
function buildFlutter() {
  const rampConsts = Object.entries(tokens.palette)
    .flatMap(([name, ramp]) =>
      Object.entries(rampSteps(ramp)).map(([step, hex]) => {
        const ident =
          name +
          step
            .split("-")
            .map((p) => p[0].toUpperCase() + p.slice(1))
            .join("");
        return `  static const Color ${ident} = ${dartColor(hex)};`;
      }),
    )
    .join("\n");

  const themeFields = ROLES.map(
    (r) => `  /// Semantic role "${r}", resolved for this theme.\n  final Color ${r};`,
  ).join("\n");
  const ctorArgs = ROLES.map((r) => `    required this.${r},`).join("\n");
  const themeConst = (name, set) =>
    `  static const DesignTokens ${name} = DesignTokens._(\n` +
    ROLES.map((r) => `    ${r}: ${dartColor(set[r])},`).join("\n") +
    `\n  );`;

  const statusEntries = Object.entries(tokens.status)
    .filter(([k]) => !k.startsWith("$"))
    .map(([status, role]) => `  '${status}': '${role}',`)
    .join("\n");

  const space = tokens.scale.space;
  const spaceConsts = Object.entries(space)
    .filter(([k]) => !k.startsWith("$"))
    .map(([k, v]) => `  static const double ${k} = ${v};`)
    .join("\n");
  const radius = tokens.scale.radius;
  const motion = tokens.scale.motion;

  return `${BANNER}

import 'package:flutter/material.dart';

/// Raw palette ramps. Screens must NOT reach for these — consume
/// [DesignTokens] roles (or [AppColors], which delegates here) instead.
/// They exist so a role can be resolved to a ramp step in one place.
class DesignPalette {
  DesignPalette._();

${rampConsts}
}

/// One theme's resolved semantic roles. Two const instances, [light] and
/// [dark], built independently rather than by inverting one another — dark is
/// a first-class theme (mandate §1.6), not light with the greys flipped.
class DesignTokens {
  const DesignTokens._({
${ctorArgs}
  });

${themeFields}

${themeConst("light", light)}

${themeConst("dark", dark)}

  static DesignTokens of(Brightness b) =>
      b == Brightness.dark ? dark : light;
}

/// Domain status -> semantic role name. ONE meaning on all four surfaces.
/// PENDING and the whole pending family resolve to "review" (cyan-teal), never
/// to "warning" — "PENDING is never red or warning-yellow" (E3.1).
const Map<String, String> kStatusRole = {
${statusEntries}
};

/// Resolve a domain status string to its colour in the active theme.
/// Unknown statuses fall back to secondary text rather than to a colour that
/// would assert a meaning the system does not have.
Color statusColor(String status, DesignTokens t) {
  switch (kStatusRole[status.toUpperCase()]) {
    case 'success':
      return t.success;
    case 'warning':
      return t.warning;
    case 'critical':
      return t.critical;
    case 'review':
      return t.review;
    default:
      return t.textSecondary;
  }
}

/// Spacing scale — ${space.$grid}
class DesignSpace {
  DesignSpace._();

${spaceConsts}
}

/// Radius scale — ${radius.$cap}
class DesignRadius {
  DesignRadius._();

  static const double input = ${radius.input};
  static const double button = ${radius.button};
  static const double card = ${radius.card};
  static const double circle = ${radius.circle};
}

/// Motion scale — shared with the web surfaces so the same gesture
/// decelerates identically everywhere.
class DesignMotion {
  DesignMotion._();

  static const Duration fast = Duration(milliseconds: ${motion.fast});
  static const Duration base = Duration(milliseconds: ${motion.base});
  static const Duration slow = Duration(milliseconds: ${motion.slow});
  static const Curve ease = Cubic(0.16, 1, 0.3, 1);
}
`;
}

// ── Admin (Mantine) ────────────────────────────────────────────────────────
// Two artifacts: the TS module theme.ts imports (tuples + roles), and the CSS
// custom properties globals.css imports. Mantine needs both — the tuples drive
// component colour props, the variables drive the hand-written CSS.
function buildAdminTs() {
  const tuple = (name) => {
    const steps = rampSteps(tokens.palette[name]);
    const ordered = ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900"]
      .map((s) => steps[s])
      .filter(Boolean);
    return `export const ${name}: MantineColorsTuple = [\n  ${ordered
      .map((h) => `"${h}"`)
      .join(", ")},\n];`;
  };

  // Mantine's `dark` tuple is index 0 = lightest text ... 9 = deepest bg.
  const p = tokens.palette.ink;
  const darkTuple = [
    p["dark-text-1"], "#CFE2F5", "#AFC8E0", p["dark-text-2"],
    resolveRef(tokens, tokens.semantic.dark.textDisabled), "#2C4C6B",
    p["dark-border"], p["dark-surface-alt"], p["dark-surface"], p["dark-bg"],
  ];

  const semanticBlock = (set) =>
    ROLES.map((r) => `    ${r}: "${set[r]}",`).join("\n");

  const statusEntries = Object.entries(tokens.status)
    .filter(([k]) => !k.startsWith("$"))
    .map(([s, role]) => `  ${s}: "${role}",`)
    .join("\n");

  return `${BANNER}

import type { MantineColorsTuple } from "@mantine/core";

${["teal", "gold", "coral", "emerald", "warn", "danger", "review"]
  .map(tuple)
  .join("\n")}

// Palette-tinted neutrals, not Mantine's slate default (mandate §1.3).
export const dark: MantineColorsTuple = [
  ${darkTuple.map((h) => `"${h}"`).join(", ")},
];

export const palettes = { teal, gold, coral, emerald, warn, danger, review, dark };

/** Resolved semantic roles per theme — the same values the other three
 *  surfaces render, because they come from the same JSON. */
export const semantic = {
  light: {
${semanticBlock(light)}
  },
  dark: {
${semanticBlock(dark)}
  },
} as const;

/** Role name -> Mantine colour key, so page code reads by role. */
export const roleColor = {
  brand: "teal",
  success: "emerald",
  warning: "warn",
  critical: "danger",
  review: "review",
  accent: "gold",
  cta: "coral",
} as const;

/** Domain status -> semantic role. ONE meaning on all four surfaces.
 *  The pending family is \`review\` (cyan-teal), never \`warning\`. */
export const statusRole = {
${statusEntries}
} as const;

export type StatusKey = keyof typeof statusRole;

/** Mantine colour key for a domain status; unknown statuses get no colour
 *  assertion, they render as muted text. */
export function statusColorKey(status: string): string | undefined {
  const role = statusRole[status.toUpperCase() as StatusKey];
  if (!role || role === "textSecondary") return undefined;
  return roleColor[role as keyof typeof roleColor];
}

export const radius = ${JSON.stringify(
    Object.fromEntries(
      Object.entries(tokens.scale.radius).filter(([k]) => !k.startsWith("$")),
    ),
  )} as const;

export const motion = ${JSON.stringify(
    Object.fromEntries(
      Object.entries(tokens.scale.motion).filter(([k]) => !k.startsWith("$")),
    ),
  )} as const;

export const shadowHairline = "0 1px 2px rgba(${tokens.scale.elevation.shadowRgbLight},.06)";
`;
}

function buildAdminCss() {
  // Admin drives dark mode off Mantine's own attribute — never a bare media
  // query. Both systems key off the same signal or they desynchronise, which
  // is a bug this surface has already had.
  const vars = (set) =>
    [
      `  --color-bg: ${set.appBg};`,
      `  --color-surface: ${set.surface};`,
      `  --color-surface-soft: ${set.surfaceAlt};`,
      `  --color-border: ${set.border};`,
      `  --color-ink: ${set.textPrimary};`,
      `  --color-muted: ${set.textSecondary};`,
      `  --color-disabled: ${set.textDisabled};`,
      `  --color-primary: ${set.brand};`,
      `  --color-on-primary: ${set.onBrand};`,
      `  --color-secondary: ${set.accent};`,
      `  --color-accent: ${set.cta};`,
      `  --color-success: ${set.success};`,
      `  --color-warning: ${set.warning};`,
      `  --color-danger: ${set.critical};`,
      `  --color-review: ${set.review};`,
    ].join("\n");

  return `${CSS_BANNER(
    "Dark mode keys off Mantine's own data-mantine-color-scheme attribute and\n   NOT a bare prefers-color-scheme query: two unsynchronised theming systems\n   on one page is a bug this surface has already shipped once.",
  )}

:root,
[data-mantine-color-scheme="light"] {
${vars(light)}
  --glow-a: ${rgba(light.brand, 0.16)};
  --glow-b: ${rgba(light.accent, 0.12)};
}

[data-mantine-color-scheme="dark"] {
${vars(dark)}
  /* Glows lift with the brand — tuned against the dark ground, not the light one. */
  --glow-a: ${rgba(dark.brand, 0.22)};
  --glow-b: ${rgba(dark.accent, 0.14)};
}
`;
}

// ── Kiosk ──────────────────────────────────────────────────────────────────
// Dark resolution only, and it keeps the kiosk's existing variable NAMES so
// the ~20 call sites referencing --teal/--violet/--amber aliases keep working.
// The viewport-derived type and spacing scales stay in theme.css: they are
// clamp() expressions against a 1080x1920 portrait panel, not token values.
function buildKioskCss() {
  const r = tokens.scale.radius;
  return `${CSS_BANNER(
    "The kiosk renders the DARK resolution only — it is a fixed public display\n   in one known lighting environment with no per-user preference to persist.",
  )}

:root {
  --bg: ${dark.appBg};
  --surf: ${dark.surface};
  --surf2: ${dark.surfaceAlt};
  --border: ${dark.border};

  --brand: ${dark.brand};
  --brand-glow: ${rgba(dark.brand, 0.35)};
  /* Retained as aliases: ~20 call sites still reference them and renaming
     every one adds risk without changing a rendered pixel. Use --brand. */
  --teal: var(--brand);
  --violet: var(--brand);
  --teal-glow: var(--brand-glow);
  --violet-glow: var(--brand-glow);

  --gold: ${dark.accent};
  --gold-glow: ${rgba(dark.accent, 0.35)};
  --amber: var(--gold);
  --amber-glow: var(--gold-glow);

  --coral: ${dark.cta};
  --coral-glow: ${rgba(dark.cta, 0.35)};

  --emerald: ${dark.success};
  --emerald-glow: ${rgba(dark.success, 0.35)};

  --warn: ${dark.warning};
  --warn-glow: ${rgba(dark.warning, 0.35)};

  --danger: ${dark.critical};
  --danger-glow: ${rgba(dark.critical, 0.35)};

  /* The pending / under-review family. Cyan-teal, deliberately distinct from
     --brand: a locker waiting on a decision must not read as a brand accent,
     and must never be warning-yellow. */
  --review: ${dark.review};
  --review-glow: ${rgba(dark.review, 0.35)};

  --ink: ${dark.textPrimary};
  --ink2: ${dark.textSecondary};
  --ink3: ${dark.textDisabled};

  /* --border is the decorative hairline; --border-strong is the 3:1 boundary
     WCAG 1.4.11 requires wherever a border is what identifies a control. */
  --border-strong: ${dark.borderStrong};

  /* Radius is capped at ${r.card}px on every surface. */
  --r-sm: ${r.input}px;
  --r-md: ${r.button}px;
  --r-lg: ${r.card}px;
  --r-xl: ${r.card}px;

  /* Kiosk-industry minimum physical finger target; nothing tappable is smaller. */
  --touch-min: clamp(${tokens.kiosk.minTouchTargetPx}px, 7vmin, 96px);

  --motion-fast: ${tokens.scale.motion.fast}ms;
  --motion-base: ${tokens.scale.motion.base}ms;
  --motion-slow: ${tokens.scale.motion.slow}ms;
  --motion-ease: ${tokens.scale.motion.ease};
}
`;
}

// ── Website ────────────────────────────────────────────────────────────────
// Both themes. The `.dark` class is driven by next-themes (app/providers.tsx)
// and toggled by components/theme-switch.tsx — the website is NOT light-only.
function buildWebCss() {
  const vars = (set) =>
    [
      `  --brand-bg: ${set.appBg};`,
      `  --brand-surface: ${set.surface};`,
      `  --brand-soft: ${set.surfaceAlt};`,
      `  --brand-border: ${set.border};`,
      `  --brand-ink: ${set.textPrimary};`,
      `  --brand-muted: ${set.textSecondary};`,
      `  --brand-primary: ${set.brand};`,
      `  --brand-secondary: ${set.accent};`,
      `  --brand-accent: ${set.cta};`,
      `  --brand-success: ${set.success};`,
      `  --brand-warning: ${set.warning};`,
      `  --brand-danger: ${set.critical};`,
      `  --brand-review: ${set.review};`,
      ``,
      `  --brand-from: ${set.brand};`,
      `  --brand-via: ${set.accent};`,
      `  --brand-to: ${set.cta};`,
    ].join("\n");

  return `${CSS_BANNER(
    "--brand-from/via/to drive Velora's aurora blobs and deliberately use all\n   three brand colours so the hero carries the full palette, not one tint.",
  )}

:root {
${vars(light)}
}

.dark {
${vars(dark)}
}
`;
}

emit("client/flutter_app/lib/core/theme/design_tokens.g.dart", buildFlutter());
emit("client/admin/src/app/design-tokens.g.ts", buildAdminTs());
emit("client/admin/src/app/design-tokens.g.css", buildAdminCss());
emit("server/kiosk/kiosk_ui_react/src/design-tokens.g.css", buildKioskCss());
emit("client/web/styles/design-tokens.g.css", buildWebCss());

if (CHECK_ONLY) {
  if (stale.length) {
    console.error("STALE — these generated files do not match tokens.json:");
    for (const f of stale) console.error(`  ${f}`);
    console.error("\nRun: node design/tokens/build.mjs");
    process.exit(1);
  }
  console.log("All generated token files are up to date with tokens.json.");
} else if (written.length) {
  console.log(`Wrote ${written.length} file(s):`);
  for (const f of written) console.log(`  ${f}`);
} else {
  console.log("No changes — generated files already match tokens.json.");
}
