// GENERATED by design/tokens/build.mjs from design/tokens/tokens.json.
// DO NOT EDIT BY HAND — edit the JSON and re-run the generator.
// Editing this file directly reintroduces exactly the four-surface drift
// E3.1 exists to remove.

import 'package:flutter/material.dart';

/// Raw palette ramps. Screens must NOT reach for these — consume
/// [DesignTokens] roles (or [AppColors], which delegates here) instead.
/// They exist so a role can be resolved to a ramp step in one place.
class DesignPalette {
  DesignPalette._();

  static const Color teal50 = Color(0xFFE6F7F5);
  static const Color teal100 = Color(0xFFC0EBE6);
  static const Color teal200 = Color(0xFF93DDD4);
  static const Color teal300 = Color(0xFF63CFC1);
  static const Color teal400 = Color(0xFF3EC3B3);
  static const Color teal500 = Color(0xFF0B5FA5);
  static const Color teal600 = Color(0xFF0A5593);
  static const Color teal700 = Color(0xFF08497F);
  static const Color teal800 = Color(0xFF073D6B);
  static const Color teal900 = Color(0xFF063157);
  static const Color tealOnDark = Color(0xFF4DA3E8);
  static const Color gold50 = Color(0xFFFEF6E7);
  static const Color gold100 = Color(0xFFFCE8C2);
  static const Color gold200 = Color(0xFFFAD89A);
  static const Color gold300 = Color(0xFFF8C86F);
  static const Color gold400 = Color(0xFFF6BA4D);
  static const Color gold500 = Color(0xFFE9A13B);
  static const Color gold600 = Color(0xFFD4902F);
  static const Color gold700 = Color(0xFFC07F22);
  static const Color gold800 = Color(0xFFA56B1A);
  static const Color gold900 = Color(0xFF8A5813);
  static const Color goldOnDark = Color(0xFFF5B85C);
  static const Color coral50 = Color(0xFFFFEEF0);
  static const Color coral100 = Color(0xFFFFD7DC);
  static const Color coral200 = Color(0xFFFFB0BA);
  static const Color coral300 = Color(0xFFFD8797);
  static const Color coral400 = Color(0xFFFC6478);
  static const Color coral500 = Color(0xFFEF6E7B);
  static const Color coral600 = Color(0xFFE05E6C);
  static const Color coral700 = Color(0xFFD14F5D);
  static const Color coral800 = Color(0xFFB8404E);
  static const Color coral900 = Color(0xFF9E323F);
  static const Color coralOnDark = Color(0xFFFF8A95);
  static const Color emerald50 = Color(0xFFE9FBEF);
  static const Color emerald100 = Color(0xFFC6F5D6);
  static const Color emerald200 = Color(0xFF9AECB8);
  static const Color emerald300 = Color(0xFF6CE399);
  static const Color emerald400 = Color(0xFF45DC80);
  static const Color emerald500 = Color(0xFF22C55E);
  static const Color emerald600 = Color(0xFF1EB054);
  static const Color emerald700 = Color(0xFF199748);
  static const Color emerald800 = Color(0xFF147E3C);
  static const Color emerald900 = Color(0xFF0F6530);
  static const Color warn50 = Color(0xFFFEF5E6);
  static const Color warn100 = Color(0xFFFCE4BD);
  static const Color warn200 = Color(0xFFFAD090);
  static const Color warn300 = Color(0xFFF8BC61);
  static const Color warn400 = Color(0xFFF6AD3D);
  static const Color warn500 = Color(0xFFF59E0B);
  static const Color warn600 = Color(0xFFE08E08);
  static const Color warn700 = Color(0xFFC67C06);
  static const Color warn800 = Color(0xFFAC6A05);
  static const Color warn900 = Color(0xFF925903);
  static const Color danger50 = Color(0xFFFDECEC);
  static const Color danger100 = Color(0xFFFBD0D0);
  static const Color danger200 = Color(0xFFF8AFAF);
  static const Color danger300 = Color(0xFFF58D8D);
  static const Color danger400 = Color(0xFFF37373);
  static const Color danger500 = Color(0xFFEF4444);
  static const Color danger600 = Color(0xFFD93C3C);
  static const Color danger700 = Color(0xFFBF3232);
  static const Color danger800 = Color(0xFFA52929);
  static const Color danger900 = Color(0xFF8B2020);
  static const Color review50 = Color(0xFFE6F7FB);
  static const Color review100 = Color(0xFFC3ECF4);
  static const Color review200 = Color(0xFF93DCEA);
  static const Color review300 = Color(0xFF5FC9DF);
  static const Color review400 = Color(0xFF33B6D1);
  static const Color review500 = Color(0xFF0E9BB8);
  static const Color review600 = Color(0xFF0C86A0);
  static const Color review700 = Color(0xFF0A6F86);
  static const Color review800 = Color(0xFF08586B);
  static const Color review900 = Color(0xFF064451);
  static const Color ink0 = Color(0xFFFFFFFF);
  static const Color inkLightBg = Color(0xFFF7F9FC);
  static const Color inkSurfaceAlt = Color(0xFFEEF4FB);
  static const Color inkBorder = Color(0xFFD5E3F2);
  static const Color inkBorderStrong = Color(0xFF6E8FB3);
  static const Color inkText2 = Color(0xFF51677F);
  static const Color inkText1 = Color(0xFF0C1F33);
  static const Color inkDarkText2 = Color(0xFF93AEC9);
  static const Color inkDarkBorder = Color(0xFF1E3A54);
  static const Color inkDarkBorderStrong = Color(0xFF43708F);
  static const Color inkDarkSurfaceAlt = Color(0xFF122740);
  static const Color inkDarkSurface = Color(0xFF0B1A2A);
  static const Color inkDarkBg = Color(0xFF050F1A);
  static const Color inkDarkText1 = Color(0xFFEEF6FF);
}

/// One theme's resolved semantic roles. Two const instances, [light] and
/// [dark], built independently rather than by inverting one another — dark is
/// a first-class theme (mandate §1.6), not light with the greys flipped.
class DesignTokens {
  const DesignTokens._({
    required this.brand,
    required this.onBrand,
    required this.success,
    required this.warning,
    required this.critical,
    required this.review,
    required this.accent,
    required this.cta,
    required this.brandInk,
    required this.successInk,
    required this.warningInk,
    required this.criticalInk,
    required this.reviewInk,
    required this.accentInk,
    required this.ctaInk,
    required this.appBg,
    required this.surface,
    required this.surfaceAlt,
    required this.border,
    required this.borderStrong,
    required this.textPrimary,
    required this.textSecondary,
    required this.textDisabled,
  });

  /// Semantic role "brand", resolved for this theme.
  final Color brand;
  /// Semantic role "onBrand", resolved for this theme.
  final Color onBrand;
  /// Semantic role "success", resolved for this theme.
  final Color success;
  /// Semantic role "warning", resolved for this theme.
  final Color warning;
  /// Semantic role "critical", resolved for this theme.
  final Color critical;
  /// Semantic role "review", resolved for this theme.
  final Color review;
  /// Semantic role "accent", resolved for this theme.
  final Color accent;
  /// Semantic role "cta", resolved for this theme.
  final Color cta;
  /// Semantic role "brandInk", resolved for this theme.
  final Color brandInk;
  /// Semantic role "successInk", resolved for this theme.
  final Color successInk;
  /// Semantic role "warningInk", resolved for this theme.
  final Color warningInk;
  /// Semantic role "criticalInk", resolved for this theme.
  final Color criticalInk;
  /// Semantic role "reviewInk", resolved for this theme.
  final Color reviewInk;
  /// Semantic role "accentInk", resolved for this theme.
  final Color accentInk;
  /// Semantic role "ctaInk", resolved for this theme.
  final Color ctaInk;
  /// Semantic role "appBg", resolved for this theme.
  final Color appBg;
  /// Semantic role "surface", resolved for this theme.
  final Color surface;
  /// Semantic role "surfaceAlt", resolved for this theme.
  final Color surfaceAlt;
  /// Semantic role "border", resolved for this theme.
  final Color border;
  /// Semantic role "borderStrong", resolved for this theme.
  final Color borderStrong;
  /// Semantic role "textPrimary", resolved for this theme.
  final Color textPrimary;
  /// Semantic role "textSecondary", resolved for this theme.
  final Color textSecondary;
  /// Semantic role "textDisabled", resolved for this theme.
  final Color textDisabled;

  static const DesignTokens light = DesignTokens._(
    brand: Color(0xFF0B5FA5),
    onBrand: Color(0xFFFFFFFF),
    success: Color(0xFF22C55E),
    warning: Color(0xFFF59E0B),
    critical: Color(0xFFEF4444),
    review: Color(0xFF0E9BB8),
    accent: Color(0xFFE9A13B),
    cta: Color(0xFFEF6E7B),
    brandInk: Color(0xFF0B5FA5),
    successInk: Color(0xFF147E3C),
    warningInk: Color(0xFF925903),
    criticalInk: Color(0xFFBF3232),
    reviewInk: Color(0xFF0A6F86),
    accentInk: Color(0xFF8A5813),
    ctaInk: Color(0xFFB8404E),
    appBg: Color(0xFFF7F9FC),
    surface: Color(0xFFFFFFFF),
    surfaceAlt: Color(0xFFEEF4FB),
    border: Color(0xFFD5E3F2),
    borderStrong: Color(0xFF6E8FB3),
    textPrimary: Color(0xFF0C1F33),
    textSecondary: Color(0xFF51677F),
    textDisabled: Color(0xFF8CA2BC),
  );

  static const DesignTokens dark = DesignTokens._(
    brand: Color(0xFF4DA3E8),
    onBrand: Color(0xFF04211D),
    success: Color(0xFF22C55E),
    warning: Color(0xFFF59E0B),
    critical: Color(0xFFF37373),
    review: Color(0xFF33B6D1),
    accent: Color(0xFFF5B85C),
    cta: Color(0xFFFF8A95),
    brandInk: Color(0xFF4DA3E8),
    successInk: Color(0xFF22C55E),
    warningInk: Color(0xFFF59E0B),
    criticalInk: Color(0xFFF37373),
    reviewInk: Color(0xFF33B6D1),
    accentInk: Color(0xFFF5B85C),
    ctaInk: Color(0xFFFF8A95),
    appBg: Color(0xFF050F1A),
    surface: Color(0xFF0B1A2A),
    surfaceAlt: Color(0xFF122740),
    border: Color(0xFF1E3A54),
    borderStrong: Color(0xFF43708F),
    textPrimary: Color(0xFFEEF6FF),
    textSecondary: Color(0xFF93AEC9),
    textDisabled: Color(0xFF5B7A96),
  );

  static DesignTokens of(Brightness b) =>
      b == Brightness.dark ? dark : light;
}

/// Domain status -> semantic role name. ONE meaning on all four surfaces.
/// PENDING and the whole pending family resolve to "review" (cyan-teal), never
/// to "warning" — "PENDING is never red or warning-yellow" (E3.1).
const Map<String, String> kStatusRole = {
  'APPROVED': 'success',
  'VERIFIED': 'success',
  'COMPLETED': 'success',
  'ACTIVE': 'success',
  'PAID': 'success',
  'ONLINE': 'success',
  'ACTIVE_USER': 'success',
  'PENDING': 'review',
  'UNDER_REVIEW': 'review',
  'MANUAL_REVIEW': 'review',
  'PROCESSING': 'review',
  'AWAITING_DEPOSIT': 'review',
  'AWAITING_CONFIRMATION': 'review',
  'VERIFICATION': 'review',
  'SUBMITTED': 'review',
  'RETRY': 'warning',
  'REJECTED': 'critical',
  'FAILED': 'critical',
  'DISPUTED': 'critical',
  'CANCELLED': 'critical',
  'OVERDUE': 'critical',
  'OFFLINE': 'critical',
  'DEPOSITED': 'accent',
  'REFUNDED': 'accent',
  'UNSUBMITTED': 'textSecondary',
  'NOT_SUBMITTED': 'textSecondary',
};

/// Resolve a domain status string to its colour in the active theme.
/// Unknown statuses fall back to secondary text rather than to a colour that
/// would assert a meaning the system does not have.
Color statusColor(String status, DesignTokens t) {
  switch (kStatusRole[status.toUpperCase()]) {
    case 'success':
      return t.success;
    case 'warning':
      return t.warning;
    case 'critical':
      return t.critical;
    case 'review':
      return t.review;
    case 'accent':
      return t.accent;
    default:
      return t.textSecondary;
  }
}

/// The on-light text/icon colour for a status. Never use [statusColor] as text
/// on a light surface: a status 500 is a fill hue and most of them sit under
/// 3:1 on white.
Color statusInk(String status, DesignTokens t) {
  switch (kStatusRole[status.toUpperCase()]) {
    case 'success':
      return t.successInk;
    case 'warning':
      return t.warningInk;
    case 'critical':
      return t.criticalInk;
    case 'review':
      return t.reviewInk;
    case 'accent':
      return t.accentInk;
    default:
      return t.textSecondary;
  }
}

/// Spacing scale — 8px, with a single 4px sub-step for icon-label gaps only
class DesignSpace {
  DesignSpace._();

  static const double hair = 4;
  static const double xs = 8;
  static const double sm = 12;
  static const double md = 16;
  static const double lg = 24;
  static const double xl = 32;
  static const double xxl = 48;
  static const double huge = 64;
}

/// Radius scale — 6px hard cap, 'machined edges not lozenges'
class DesignRadius {
  DesignRadius._();

  static const double input = 2;
  static const double button = 4;
  static const double card = 6;
  static const double circle = 999;
}

/// Motion scale — shared with the web surfaces so the same gesture
/// decelerates identically everywhere.
class DesignMotion {
  DesignMotion._();

  static const Duration fast = Duration(milliseconds: 160);
  static const Duration base = Duration(milliseconds: 260);
  static const Duration slow = Duration(milliseconds: 420);
  static const Curve ease = Cubic(0.16, 1, 0.3, 1);
}

/// Interaction states, shared with the three CSS surfaces so a press means the
/// same depth everywhere. Material supplies its own overlays; these are the
/// values app_theme.dart feeds it, so the ripple and the kiosk's press
/// feedback come from ONE number rather than two that merely look alike.
class DesignInteraction {
  DesignInteraction._();

  static const double hoverOverlay = 0.08;
  static const double activeOverlay = 0.14;
  static const double selectedOverlay = 0.12;
  static const double disabledOpacity = 0.45;

  /// Focus indicator. WCAG 1.4.11 governs a focus ring exactly as it governs a
  /// control border, which is why this is the brand role and not a hairline.
  static const double focusRingWidth = 3;
  static const double focusRingOffset = 2;
}
